doctrine_fixtures:
    loaders:
        default:
            fixtures:
                - App\DataFixtures\UserFixtures
                - App\DataFixtures\AppFixtures
                - App\DataFixtures\ReservationFixtures